name: Matrix Notification
description: Send a notification via Matrix
author: Lars Kiesow
inputs:
  server:
    required: true
    description: The Matrix home server to send the message to
    default: matrix.org
  token:
    required: true
    description: Secret token used for authentication
  room:
    required: true
    description: The room to send the message to
  message:
    required: false
    description: The message to send
  formatted_message:
    required: false
    description: An HTML formatted version of the message to send
  tool:
    required: true
    description: If to install the matrix-msg binary
    default: false
runs:
  using: node16
  main: dist/index.js
